wcs_coav_plane_model:
    resource: "@WCSCoavBundle/Controller/PlaneModelController.php"
    type:     annotation

wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
